name: Staging Auto-PR
on: push
#   push:
#     branches: ['remote']
#     paths:
#     - '/'
jobs:
  curl:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: apt update && apt install -y curl && curl -X POST -H "Accept:application/vnd.github.v3+json" https://api.github.com/repos/chanchal-19/poc-terraform-iac/pulls -d '{"head":"remote","base":"main", "title":"New Pull request"}' -u "chanchal-19:${{ secrets.GITHUB_TOKEN }}"
#      - uses: actions/checkout@master
#      - name: curl
#        uses: wei/curl@v1
#        with:
#          args: -X POST  -u "chanchal-19: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" -H "Accept:\application/vnd.github.v3+json" https://api.github.com/repos/chanchal-19/poc-terraform-iac/pulls -d '{"head":"remote","base":"main", "title":"New Pull request"}' 
