on:
  push:
    branches:
    - remote
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: gcp_module/pull-request@remote
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
