name: Staging Auto-PR
on:
  push:
    branches: ['remote']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses:  chanchal-19/poc-terraform-iac@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "An automated PR"
        pr_reviewer: "chanchal-19"
        github_token: ${{ secrets.GITHUB_TOKEN }}
